apiVersion: v1
entries:
  nginx:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2022-08-01T13:36:41.731885-05:00"
    description: A Helm chart for Kubernetes
    digest: 52140ae68692e9e202a190994ebc98aa1e9590cf7952f5bf072dd5173e5bace4
    name: nginx
    type: application
    urls:
    - https://github.com/jjtroberts/helm-charts/nginx-0.1.0.tgz
    version: 0.1.0
generated: "2022-08-01T13:36:41.730641-05:00"
